"""empty message

Revision ID: 994edd9e9018
Revises: 71f00b004c95
Create Date: 2023-01-14 17:30:02.439599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994edd9e9018'
down_revision = '71f00b004c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fav_char',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('characters_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_fav_char')
    # ### end Alembic commands ###
